{
 "title": "Real Estate Prediction Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Панель 6: Количество HTTP запросов",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_bucket{instance=\"ml_service:1702\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Панель 5: Загрузка процессора CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Панель 4: Последнее предсказанное значение (Gauge)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_prediction_value{instance=\"ml_service:1702\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Панель 3: Распределение предсказанных цен (Histogram)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "real_estate_price_predictions_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Панель 1: Количество запросов (Counter)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "prediction_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Панель 2: Ошибочные запросы (Counter)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    { "expr": "invalid_request_count_total", "legendFormat": "__auto" }
   ]
  }
 ]
}